export const anneMarieTxData = [
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];
export const EdwardJamesonTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];
export const GlennAwongTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];
export const SmithBrownTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];

export const AlexaWilliamsTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Feb 15, 2024",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Jan 2, 2024",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2021",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2021",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2020",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2010",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2010",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2008",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2000",
    color: "red",
  },
];

export const JamesFletcherTxData = [
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Nov 15, 2023",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "July 2, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Mar 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jan 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$270,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2022",
    color: "red",
  },
  {
    txName: "Thumann Agency, Inc",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2021",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Apr 25, 2021",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2021",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2020",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2020",
    color: "red",
  },
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 15, 2019",
    color: "green",
  },
  {
    txName: "Texas Funding Corporation",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "July 2, 2019",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$375,000.00",
    date: "Oct 21, 2015",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "April 25, 2015",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jan 19, 2015",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2013",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2013",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2013",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2013",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Debit",
    debit: "-$15,000.00",
    date: "Apr 25, 2012",
    color: "red",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2011",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2011",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2011",
    color: "red",
  },
  {
    txName: "CSG Insurance Services, Inc.",
    whatUsed: "Credit",
    debit: "+$358,642.00",
    date: "May 01, 2010",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2010",
    color: "green",
  },
  {
    txName: "Deepenough clothing",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2009",
    color: "green",
  },
  {
    txName: "Rig Component Manufacturing",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2009",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$1085.00",
    date: "Jan 1, 2009",
    color: "red",
  },
];

export const GregoryHartmannTxData = [
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$800,000.00",
    date: " April 10, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$250,000.00",
    date: "Feb 18, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Jan 20, 2024",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Mar 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jan 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$270,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2022",
    color: "red",
  },
  {
    txName: "Thumann Agency, Inc",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2021",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Apr 25, 2021",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2021",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2020",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2020",
    color: "red",
  },
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 15, 2019",
    color: "green",
  },
  {
    txName: "Texas Funding Corporation",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "July 2, 2019",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$375,000.00",
    date: "Oct 21, 2015",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "April 25, 2015",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jan 19, 2015",
    color: "green",
  },
];

export const ElsaMichelleJeffersonTxData = [
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$800,000.00",
    date: " April 10, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$250,000.00",
    date: "Feb 18, 2024",
    color: "green",
  },
  {
    txName: "Armor Texas Insurance Agency, Inc.",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Jan 20, 2024",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Mar 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jan 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$270,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2022",
    color: "red",
  },
  {
    txName: "Thumann Agency, Inc",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2022",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2021",
    color: "green",
  },
  {
    txName: "Safe insurance Services",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Apr 25, 2021",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2021",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2020",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2020",
    color: "red",
  },
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 15, 2019",
    color: "green",
  },
  {
    txName: "Texas Funding Corporation",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "July 2, 2019",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$375,000.00",
    date: "Oct 21, 2015",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "April 25, 2015",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jan 19, 2015",
    color: "green",
  },
];

export const TanyaTateThomasTxData = [
  {
    txName: "Thomas Ullrich",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "May 25, 2024",
    color: "red",
  },
  {
    txName: "X-RATED CRITICS ORGANIZATION",
    whatUsed: "Credit",
    debit: "+$5,000,000.00",
    date: " May 23, 2024",
    color: "green",
  },
  {
    txName: "X-RATED CRITICS ORGANIZATION",
    whatUsed: "Credit",
    debit: "+$2,100,000.00",
    date: "May 16, 2024",
    color: "green",
  },
  {
    txName: "X-RATED CRITICS ORGANIZATION",
    whatUsed: "Credit",
    debit: "+$2,000,000.00",
    date: "Feb 16, 2024",
    color: "green",
  },
];