export const anneMarieTxData = [
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];
export const EdwardJamesonTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];
export const GlennAwongTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];
export const SmithBrownTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Nov 22, 2023",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2023",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2023",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2023",
    color: "red",
  },
];

export const AlexaWilliamsTxData = [
  {
    txName: "Power Ball Lottery",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Feb 15, 2024",
    color: "green",
  },
  {
    txName: "#23190129",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "Jan 2, 2024",
    color: "green",
  },
  {
    txName: "Mary Lou Roush Winings",
    whatUsed: "Credit",
    debit: "+$350,000.00",
    date: "Nov 21, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 19, 2022",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 05, 2022",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "May 18, 2021",
    color: "red",
  },
  {
    txName: "Slite SASS",
    whatUsed: "Credit",
    debit: "+$208,000.00",
    date: "May 05, 2021",
    color: "green",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2020",
    color: "green",
  },
  {
    txName: "WeWork Loan",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Apr 25, 2010",
    color: "green",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2010",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2008",
    color: "green",
  },
  {
    txName: "Walmart",
    whatUsed: "Debit",
    debit: "-$185.00",
    date: "Jan 1, 2000",
    color: "red",
  },
];